/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdoctor.appointment.view.appointment;

import java.util.ArrayList;
import jdoctor.appointment.controller.DoctorController;
import jdoctor.appointment.model.Doctor;
import jdoctor.appointment.util.GuiUtils;

/**
 *
 * @author aug
 */
public class AppointmentForm extends javax.swing.JPanel {
    private DoctorController doctorController;
    /**
     * Creates new form AppointmentForm
     */
    public AppointmentForm() {
        initComponents();
    }
    
    public void setDate() {
        doctorController = new DoctorController();
        medicTablePanel.setHeader("Medico");
        ArrayList<ArrayList<String>> doctors = new ArrayList<>();
        
        try {
            for (Doctor doctor : doctorController.getAll()) {
                ArrayList<String> array = new ArrayList<>();
                array.add(doctor.getId().toString());
                array.add(doctor.getName());
                doctors.add(array);
            }
        } catch (Exception e) {
            GuiUtils.showErrorOkDialog(e.getMessage(), this);
        }
        
        medicTablePanel.setData(doctors);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        errorPanel = new jdoctor.appointment.view.error.ErrorPanel();
        form = new javax.swing.JPanel();
        lblHeader1 = new javax.swing.JLabel();
        medicTablePanel = new jdoctor.appointment.view.tables.StringTablePanel();

        setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        add(errorPanel, gridBagConstraints);

        form.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(form, gridBagConstraints);

        lblHeader1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader1.setText("CONSULTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        add(lblHeader1, gridBagConstraints);

        medicTablePanel.setPreferredSize(new java.awt.Dimension(460, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(medicTablePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jdoctor.appointment.view.error.ErrorPanel errorPanel;
    private javax.swing.JPanel form;
    private javax.swing.JLabel lblHeader1;
    private jdoctor.appointment.view.tables.StringTablePanel medicTablePanel;
    // End of variables declaration//GEN-END:variables
}
