package jdoctor.appointment.view.appointment;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.Calendar;
import javax.swing.JLabel;


public class AppointmentMain extends javax.swing.JPanel {
    private Calendar day;
    private CardLayout layout;
    /**
     * Creates new form AppointmentDateForm
     */
    public AppointmentMain() {
        initComponents();
        
        layout = (CardLayout) getLayout();
        
        setDate(Calendar.getInstance());
        for (int i = 0; i < 24; i++) {
            JLabel label = new JLabel(""+i+":00");
            label.setFont(new Font(label.getName(), Font.PLAIN, 12));
            label.setHorizontalAlignment(JLabel.CENTER);
            label.setMinimumSize(new Dimension(50, timesPanel.getHeight()/24));
            
            if((i & 1) == 0) {
                label.setBackground(Color.GRAY);
            }
            timesPanel.add(label);
        }
    }
    
    public void switchForm() {
        appointmentForm.setDate();
        layout.show(this, "cardForm");
    }
    
    public void setDate(Calendar day) {
        this.day = day;
        panelDays.removeAll();
        panelDays.setLayout(new GridLayout(1, 7, 2, 0));
        for (int i = 0; i < 7; i++) {
            boolean color = false;
            if ( (i & 1) == 0 ) {
                color = true;
            }
            
            Calendar aux = Calendar.getInstance();
            aux.setTime(day.getTime());
            aux.add(Calendar.DAY_OF_WEEK, i);
            
            panelDays.add(new DayPanel(aux, color, this));
        }
        panelDays.revalidate();
        panelDays.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelDays = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        arrowsPanel = new javax.swing.JPanel();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        timesPanel = new javax.swing.JPanel();
        appointmentForm = new jdoctor.appointment.view.appointment.AppointmentForm();

        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        panelDays.setLayout(new java.awt.GridLayout(1, 7, 2, 0));
        jScrollPane1.setViewportView(panelDays);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        arrowsPanel.setMinimumSize(new java.awt.Dimension(80, 58));
        arrowsPanel.setPreferredSize(new java.awt.Dimension(100, 58));
        arrowsPanel.setLayout(new java.awt.GridLayout(1, 0));

        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Arrow Left.png"))); // NOI18N
        btnLeft.setMaximumSize(new java.awt.Dimension(40, 40));
        btnLeft.setMinimumSize(new java.awt.Dimension(40, 40));
        btnLeft.setPreferredSize(new java.awt.Dimension(40, 40));
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        arrowsPanel.add(btnLeft);

        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Arrow Rigth.png"))); // NOI18N
        btnRight.setMaximumSize(new java.awt.Dimension(40, 40));
        btnRight.setMinimumSize(new java.awt.Dimension(40, 40));
        btnRight.setPreferredSize(new java.awt.Dimension(40, 40));
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        arrowsPanel.add(btnRight);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(arrowsPanel, gridBagConstraints);

        timesPanel.setBackground(new java.awt.Color(204, 204, 204));
        timesPanel.setForeground(new java.awt.Color(255, 255, 255));
        timesPanel.setMinimumSize(new java.awt.Dimension(75, 0));
        timesPanel.setPreferredSize(new java.awt.Dimension(25, 100));
        timesPanel.setLayout(new java.awt.GridLayout(24, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(timesPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(jPanel2, gridBagConstraints);

        add(jPanel1, "cardData");
        add(appointmentForm, "cardForm");
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        day.add(Calendar.DAY_OF_WEEK, -6);
        setDate(day);
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        day.add(Calendar.DAY_OF_WEEK, +6);
        setDate(day);
    }//GEN-LAST:event_btnRightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jdoctor.appointment.view.appointment.AppointmentForm appointmentForm;
    private javax.swing.JPanel arrowsPanel;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDays;
    private javax.swing.JPanel timesPanel;
    // End of variables declaration//GEN-END:variables
}
