/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdoctor.appointment.view.appointment;

import java.awt.Color;
import java.awt.MouseInfo;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import lombok.Setter;

/**
 *
 * @author aug
 */
public class DayPanel extends javax.swing.JPanel {
    private Calendar calendar;
    private final SimpleDateFormat sdf;
    private final SimpleDateFormat date;
    private final SimpleDateFormat day;
    @Setter
    private AppointmentMain appointmentMain;
    /**
     * Creates new form DayPanel
     */
    public DayPanel(Calendar calendar, boolean pair, AppointmentMain appointmentMain) {
        initComponents();
        
        this.appointmentMain = appointmentMain;
        
        this.calendar = calendar;
        sdf = new SimpleDateFormat("HH:mm");
        date = new SimpleDateFormat("dd/mm/yyyy");
        day = new SimpleDateFormat("EEEEE");
        lblTime.setText("00:00");
        lblTime.setVisible(false);
        
        if (pair) {
            panelAppointments.setBackground(new Color(230, 230, 230));
            headerPanel.setBackground(new Color(200, 200, 200));
        } else {
            panelAppointments.setBackground(new Color(220, 220, 220));
            headerPanel.setBackground(new Color(190, 190, 190));
        }
        
        lblDay.setText(date.format(calendar.getTime()));
        lblDayString.setText(day.format(calendar.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        lblDay = new javax.swing.JLabel();
        lblDayString = new javax.swing.JLabel();
        panelAppointments = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        headerPanel.setBackground(new java.awt.Color(204, 204, 204));
        headerPanel.setLayout(new java.awt.GridLayout(2, 0, 0, 6));

        lblDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDay.setText("XX/XX/XX");
        lblDay.setPreferredSize(new java.awt.Dimension(100, 25));
        headerPanel.add(lblDay);

        lblDayString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDayString.setText("jLabel2");
        headerPanel.add(lblDayString);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(headerPanel, gridBagConstraints);

        panelAppointments.setBackground(new java.awt.Color(255, 51, 51));
        panelAppointments.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelAppointmentsMouseMoved(evt);
            }
        });
        panelAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAppointmentsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAppointmentsMouseExited(evt);
            }
        });
        panelAppointments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setText("jLabel3");
        panelAppointments.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        add(panelAppointments, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void panelAppointmentsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAppointmentsMouseMoved
        calendar.set(2019, 6, 20, 0, 0, 0);
        // TODO add your handling code here:
        Integer posx = MouseInfo.getPointerInfo().getLocation().x 
                - panelAppointments.getLocationOnScreen().x;
        
        Integer posy = MouseInfo.getPointerInfo().getLocation().y 
                - panelAppointments.getLocationOnScreen().y;
        
        Float maxMinutes = 288f;
        Integer minMinutes = 0;
        
        Float step = (maxMinutes /panelAppointments.getHeight());
        
        Integer minute = Math.round(step*posy)*5;
        
        calendar.add(Calendar.MINUTE, minute);
        lblTime.setText(sdf.format(calendar.getTime()));
        
        //time
        lblTime.setVisible(true);
        if (posy > lblTime.getHeight()) {
          //lblTime.setBounds(32, 100, 5, posy-lblTime.getHeight());
          panelAppointments.setLayout(null);
          lblTime.setLocation(5, posy-lblTime.getHeight());  
        }
    }//GEN-LAST:event_panelAppointmentsMouseMoved

    private void panelAppointmentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAppointmentsMouseExited
        lblTime.setVisible(false);
    }//GEN-LAST:event_panelAppointmentsMouseExited

    private void panelAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAppointmentsMouseClicked
        System.out.println("oiii");
        appointmentMain.switchForm();
    }//GEN-LAST:event_panelAppointmentsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDayString;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel panelAppointments;
    // End of variables declaration//GEN-END:variables
}
