/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdoctor.appointment.view.appointment;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import jdoctor.appointment.model.Appointment;
import lombok.Setter;

/**
 *
 * @author aug
 */
public class DoctorAppointmentView extends javax.swing.JPanel {
    private final SimpleDateFormat sdf;
    @Setter
    private AppointmentMain main;
    /**
     * Creates new form DoctorAppointmentView
     */
    public DoctorAppointmentView() {
        initComponents();
        sdf = new SimpleDateFormat("HH:mm");
    }
    
    public void setDate(Appointment appointment) {
        lblSecretaryName.setText(appointment.getSecretary().getName());
        
        // Tempo
        Calendar aux = Calendar.getInstance();
        
        aux.setTime(appointment.getData().getTime());
        
        lblStartTime.setText(sdf.format(aux.getTime()));
        
        aux.add(Calendar.MINUTE, appointment.getDuration());
        
        lblEndTime.setText(sdf.format(aux.getTime()));
        
        personFormPanel1.setForm(appointment.getPerson());
        personFormPanel1.setViewMode();
        
        txtAnnotations.setText(appointment.getDescription());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblSecretaryName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblStart = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblStart3 = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        personFormPanel1 = new jdoctor.appointment.view.form.PersonFormPanel();
        lblHeaderUser2 = new javax.swing.JLabel();
        lblHeaderUser3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnnotations = new javax.swing.JTextArea();
        btnActions = new javax.swing.JPanel();
        Voltar = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblSecretaryName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSecretaryName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSecretaryName.setText("[NOME]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 18, 0);
        add(lblSecretaryName, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStart.setText("Inicio:");
        jPanel1.add(lblStart);

        lblStartTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStartTime.setText("00:00");
        jPanel1.add(lblStartTime);

        lblStart3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStart3.setText("Fim:");
        jPanel1.add(lblStart3);

        lblEndTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndTime.setText("00:00");
        jPanel1.add(lblEndTime);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(personFormPanel1, gridBagConstraints);

        lblHeaderUser2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHeaderUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderUser2.setText("Anotações");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 18, 0);
        add(lblHeaderUser2, gridBagConstraints);

        lblHeaderUser3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHeaderUser3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHeaderUser3.setText("Marcado por: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 18, 5);
        add(lblHeaderUser3, gridBagConstraints);

        txtAnnotations.setEditable(false);
        txtAnnotations.setColumns(20);
        txtAnnotations.setRows(5);
        jScrollPane1.setViewportView(txtAnnotations);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        btnActions.setLayout(new java.awt.GridLayout(1, 0));

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        btnActions.add(Voltar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        add(btnActions, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        main.switchCalendar();
    }//GEN-LAST:event_VoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JPanel btnActions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblHeaderUser2;
    private javax.swing.JLabel lblHeaderUser3;
    private javax.swing.JLabel lblSecretaryName;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblStart3;
    private javax.swing.JLabel lblStartTime;
    private jdoctor.appointment.view.form.PersonFormPanel personFormPanel1;
    private javax.swing.JTextArea txtAnnotations;
    // End of variables declaration//GEN-END:variables
}
