package jdoctor.appointment.view;

import com.jtattoo.plaf.smart.SmartLookAndFeel;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.UIManager;
import jdoctor.appointment.util.Connection;
import jdoctor.appointment.util.FinalStrings;

public class MainFrame extends javax.swing.JFrame {
    CardLayout layout;
    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
        mainLoginPanel.setMainFrame(this);
        layout = (CardLayout) getContentPane().getLayout();
        switchLogin();
    }
    
    public void switchLogin() {
        layout.show(getContentPane(), "cardLogin");
        setTitle(FinalStrings.titleSub+" Login");
    }
    
    public void switchHome(String userNick) {
        layout.show(getContentPane(), "cardHome");
        setTitle(FinalStrings.titleSub+" Pagina Inicial");
        System.out.println("Loguei como "+userNick);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLoginPanel = new jdoctor.appointment.view.docuser.MainLoginPanel();
        homePanel = new jdoctor.appointment.view.home.HomePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        mainLoginPanel.setMinimumSize(new java.awt.Dimension(400, 750));
        getContentPane().add(mainLoginPanel, "card2");
        getContentPane().add(homePanel, "cardHome");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // select the Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
        } catch (Exception e) {
            System.out.println("Falha ao usar JTatto");
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jdoctor.appointment.view.home.HomePanel homePanel;
    private jdoctor.appointment.view.docuser.MainLoginPanel mainLoginPanel;
    // End of variables declaration//GEN-END:variables
}
