package jdoctor.appointment.view.doctor;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import jdoctor.appointment.controller.DoctorController;
import jdoctor.appointment.exception.ControllerException;
import jdoctor.appointment.model.AvailableSchedule;
import jdoctor.appointment.model.Doctor;
import jdoctor.appointment.util.GuiUtils;
import jdoctor.appointment.view.tables.ScheduleTable;


public class EditSchedulePanel extends javax.swing.JPanel {
    private Doctor doctor;
    private DoctorController doctorController;
    
    public EditSchedulePanel() {
        initComponents();
        MondayTable.setMainSchedule(this);
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
        AvailableSchedule schedule = doctor.getAvailableSchedule();
        MondayTable.setDates(schedule.getOnMonday(), "MONDAY");
        TuesdayTable.setDates(schedule.getOnTuesday(), "TUESDAY");
        WednesdayTable.setDates(schedule.getOnWednesday(), "WEDNESDAY");
        ThursdayTable.setDates(schedule.getOnThursday(), "THURSDAY");
        FridayTable.setDates(schedule.getOnFriday(), "FRIDAY");
        SaturdayTable.setDates(schedule.getOnSaturday(), "SATURDAY");
        SundayTable.setDates(schedule.getOnSunday(), "SUNDAY");
    }
    
    public void save(List<Date> dates, String day) {
        switch (day) {
            case "MONDAY":
                doctor.getAvailableSchedule().setOnMonday(dates);
                break;
            case "TUESDAY":
                doctor.getAvailableSchedule().setOnTuesday(dates);
                break;
            case "WEDNESDAY":
                doctor.getAvailableSchedule().setOnWednesday(dates);
                break;
            case "THURSDAY":
                doctor.getAvailableSchedule().setOnThursday(dates);
                break;
            case "FRIDAY":
                doctor.getAvailableSchedule().setOnFriday(dates);
                break;
            case "SATURDAY":
                doctor.getAvailableSchedule().setOnSaturday(dates);
                break;
            case "SUNDAY":
                doctor.getAvailableSchedule().setOnSunday(dates);
                break;
        }
        
        doctorController = new DoctorController();
        try {
            doctorController.save(doctor);
            setDoctor(doctor);
            GuiUtils.showConfirmOkDialog("Horarios salvos! :)", this);
        } catch (ControllerException e) {
            GuiUtils.showErrorOkDialog("Falha ao salvar horarios: "+e.getMessage(), this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        MondayTable = new jdoctor.appointment.view.doctor.ScheduleTablePanel();
        TuesdayTable = new jdoctor.appointment.view.doctor.ScheduleTablePanel();
        WednesdayTable = new jdoctor.appointment.view.doctor.ScheduleTablePanel();
        ThursdayTable = new jdoctor.appointment.view.doctor.ScheduleTablePanel();
        FridayTable = new jdoctor.appointment.view.doctor.ScheduleTablePanel();
        SaturdayTable = new jdoctor.appointment.view.doctor.ScheduleTablePanel();
        SundayTable = new jdoctor.appointment.view.doctor.ScheduleTablePanel();

        setLayout(new java.awt.CardLayout());

        tabbedPane.addTab("Segunda", MondayTable);
        tabbedPane.addTab("Terça", TuesdayTable);
        tabbedPane.addTab("Quarta", WednesdayTable);
        tabbedPane.addTab("Quinta", ThursdayTable);
        tabbedPane.addTab("Sexta", FridayTable);
        tabbedPane.addTab("Sabado", SaturdayTable);
        tabbedPane.addTab("Domingo", SundayTable);

        add(tabbedPane, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jdoctor.appointment.view.doctor.ScheduleTablePanel FridayTable;
    private jdoctor.appointment.view.doctor.ScheduleTablePanel MondayTable;
    private jdoctor.appointment.view.doctor.ScheduleTablePanel SaturdayTable;
    private jdoctor.appointment.view.doctor.ScheduleTablePanel SundayTable;
    private jdoctor.appointment.view.doctor.ScheduleTablePanel ThursdayTable;
    private jdoctor.appointment.view.doctor.ScheduleTablePanel TuesdayTable;
    private jdoctor.appointment.view.doctor.ScheduleTablePanel WednesdayTable;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
