/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdoctor.appointment.view.docuser;

import jdoctor.appointment.controller.DocUserController;
import jdoctor.appointment.util.GuiUtils;
import lombok.Setter;

/**
 *
 * @author aug
 */
public class LoginPanel extends javax.swing.JPanel {
    @Setter
    private MainLoginPanel main;
    
    private DocUserController docUserController;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logoPanel1 = new jdoctor.appointment.view.misc.LogoPanel();
        formPanel = new javax.swing.JPanel();
        lblUserNick = new javax.swing.JLabel();
        txtUserNick = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        pasPassword = new javax.swing.JPasswordField();
        actionsPanel = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 17, 0);
        add(logoPanel1, gridBagConstraints);

        formPanel.setMaximumSize(new java.awt.Dimension(700, 100));
        formPanel.setMinimumSize(new java.awt.Dimension(200, 100));
        formPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        formPanel.setLayout(new java.awt.GridBagLayout());

        lblUserNick.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserNick.setText("Usuario");
        lblUserNick.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 10);
        formPanel.add(lblUserNick, gridBagConstraints);

        txtUserNick.setFont(txtUserNick.getFont().deriveFont(txtUserNick.getFont().getSize()+3f));
        txtUserNick.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        formPanel.add(txtUserNick, gridBagConstraints);

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPass.setText("Senha");
        lblPass.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        formPanel.add(lblPass, gridBagConstraints);

        pasPassword.setFont(pasPassword.getFont().deriveFont(pasPassword.getFont().getSize()+3f));
        pasPassword.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        formPanel.add(pasPassword, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        add(formPanel, gridBagConstraints);

        actionsPanel.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        actionsPanel.add(btnRegister);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        actionsPanel.add(btnLogin);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(actionsPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        main.switchRegister();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        docUserController = new DocUserController();
        try {
            docUserController.login(txtUserNick.getText(), pasPassword.getText());
            main.loginSucess(txtUserNick.getText());
        } catch (Exception e) {
            GuiUtils.showErrorOkDialog(e.getMessage(), this);
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUserNick;
    private jdoctor.appointment.view.misc.LogoPanel logoPanel1;
    private javax.swing.JPasswordField pasPassword;
    private javax.swing.JTextField txtUserNick;
    // End of variables declaration//GEN-END:variables
}
