package jdoctor.appointment.view.docuser;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import jdoctor.appointment.util.FinalStrings;
import jdoctor.appointment.view.MainFrame;
import lombok.Setter;


public class MainLoginPanel extends javax.swing.JPanel {
    @Setter
    private MainFrame mainFrame;
    private CardLayout cardLayout;
    
    public MainLoginPanel() {
        initComponents();
        cardLayout = (CardLayout) getLayout();
        loginPanel.setMain(this);
        registerFormPanel1.setMain(this);
    }

    public void switchLogin() {
        mainFrame.setTitle(FinalStrings.titleSub+" Login");
        cardLayout.show(this, "cardLogin");
    }
    
    public void switchRegister() {
        mainFrame.setTitle(FinalStrings.titleSub+" Registrar");
        cardLayout.show(this, "cardRegister");
        registerFormPanel1.cleanForm();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginPanel = new jdoctor.appointment.view.docuser.LoginPanel();
        scrollRegister = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        registerFormPanel1 = new jdoctor.appointment.view.docuser.RegisterPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.CardLayout());

        loginPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                loginPanelComponentShown(evt);
            }
        });
        add(loginPanel, "cardLogin");

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 750));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        registerFormPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        registerFormPanel1.setMaximumSize(new java.awt.Dimension(700, 2147483647));
        registerFormPanel1.setMinimumSize(new java.awt.Dimension(300, 558));
        registerFormPanel1.setPreferredSize(new java.awt.Dimension(500, 558));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(registerFormPanel1, gridBagConstraints);

        scrollRegister.setViewportView(jPanel1);

        add(scrollRegister, "cardRegister");
    }// </editor-fold>//GEN-END:initComponents

    private void loginPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_loginPanelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPanelComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if (mainFrame == null) {
            mainFrame = (MainFrame) SwingUtilities.getAncestorOfClass(
                    MainFrame.class, this);
        }
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private jdoctor.appointment.view.docuser.LoginPanel loginPanel;
    private jdoctor.appointment.view.docuser.RegisterPanel registerFormPanel1;
    private javax.swing.JScrollPane scrollRegister;
    // End of variables declaration//GEN-END:variables
}
